export const COMMENTS_CREATE = 'COMMENTS_CREATE';
export const COMMENTS_READ = 'COMMENTS_READ';
export const COMMENTS_UPDATE = 'COMMENTS_UPDATE';
export const COMMENTS_DELETE = 'COMMENTS_DELETE';
export const COMMENTS_ERROR = 'COMMENTS_ERROR';
