/// REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

/// USER
export const USER_LOADED = 'USER_LOADED';
export const USER_NOT_LOADED = 'USER_NOT_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

/// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

/// RESET PASSWORD
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

/// NEW PASSWORD
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS';
export const NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL';

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
