export const COMMENT_CREATE = 'COMMENT_CREATE';
export const COMMENT_READ = 'COMMENT_READ';
export const COMMENT_UPDATE = 'COMMENT_UPDATE';
export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_LIKES_UPDATE = 'COMMENT_LIKES_UPDATE';
export const COMMENT_ERROR = 'COMMENT_ERROR';
