export const PROFILES_CREATE = 'PROFILES_CREATE';
export const PROFILES_READ = 'PROFILES_READ';
export const PROFILES_UPDATE = 'PROFILES_UPDATE';
export const PROFILES_UPDATE_SELECTED = 'PROFILES_UPDATE_SELECTED';
export const PROFILES_DELETE = 'PROFILES_DELETE';
export const PROFILES_DELETE_SELECTED = 'PROFILES_DELETE_SELECTED';
export const PROFILES_ERROR = 'PROFILES_ERROR';
