export const PROFILE_CREATE = 'PROFILE_CREATE';
export const PROFILE_READ = 'PROFILE_READ';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_DELETE = 'PROFILE_DELETE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_CLEAR = 'PROFILE_CLEAR';
